# Generated by Django 5.2.7 on 2025-10-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Questionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("ville_depart", models.CharField(max_length=100)),
                ("ville_arrivee", models.CharField(max_length=100)),
                ("type_transport", models.CharField(max_length=100)),
                ("date_reponse", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
