# Generated by Django 5.2.7 on 2025-10-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etude_marche", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanFinancement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_projet", models.CharField(max_length=100)),
                ("montant_total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("apport_propre", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "financement_banque",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "autres_financements",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Reponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("ville_depart", models.CharField(max_length=100)),
                ("ville_arrivee", models.CharField(max_length=100)),
                ("type_transport", models.CharField(max_length=100)),
                ("date_reponse", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name="questionnaire",
            old_name="date_reponse",
            new_name="date_remplissage",
        ),
        migrations.RemoveField(
            model_name="questionnaire",
            name="type_transport",
        ),
        migrations.RemoveField(
            model_name="questionnaire",
            name="ville_arrivee",
        ),
        migrations.RemoveField(
            model_name="questionnaire",
            name="ville_depart",
        ),
        migrations.AddField(
            model_name="questionnaire",
            name="age",
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="questionnaire",
            name="prenom",
            field=models.CharField(default="Anonyme", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="questionnaire",
            name="q1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="questionnaire",
            name="q2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="questionnaire",
            name="q3",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="questionnaire",
            name="sexe",
            field=models.CharField(
                choices=[("H", "Homme"), ("F", "Femme")], default="H", max_length=1
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="questionnaire",
            name="ville",
            field=models.CharField(default="Paris", max_length=100),
            preserve_default=False,
        ),
    ]
