# Generated by Django 5.2.7 on 2025-10-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etude_marche", "0002_planfinancement_reponse_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questionnaire",
            name="email",
        ),
        migrations.RemoveField(
            model_name="questionnaire",
            name="nom",
        ),
        migrations.RemoveField(
            model_name="questionnaire",
            name="q1",
        ),
        migrations.RemoveField(
            model_name="questionnaire",
            name="q2",
        ),
        migrations.RemoveField(
            model_name="questionnaire",
            name="q3",
        ),
        migrations.AddField(
            model_name="questionnaire",
            name="budget",
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="questionnaire",
            name="frequence_voyage",
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="questionnaire",
            name="interet_transport",
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="questionnaire",
            name="prenom",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="questionnaire",
            name="sexe",
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name="questionnaire",
            name="ville",
            field=models.CharField(max_length=50),
        ),
    ]
