# Generated by Django 5.2.7 on 2025-10-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "etude_marche",
            "0003_remove_questionnaire_email_remove_questionnaire_nom_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnaire",
            name="moyen_paiement",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="questionnaire",
            name="sensibilite_prix",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="questionnaire",
            name="services_souhaites",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="questionnaire",
            name="type_colis",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="questionnaire",
            name="budget",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="questionnaire",
            name="frequence_voyage",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
