# Generated by Django 5.2.7 on 2025-10-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etude_marche", "0004_questionnaire_moyen_paiement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnaire",
            name="adresse_postale",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="questionnaire",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="questionnaire",
            name="nom",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="questionnaire",
            name="telephone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
