# Generated by Django 5.2.7 on 2025-10-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "etude_marche",
            "0005_questionnaire_adresse_postale_questionnaire_email_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="reponse",
            old_name="date_reponse",
            new_name="date_remplissage",
        ),
        migrations.RemoveField(
            model_name="reponse",
            name="type_transport",
        ),
        migrations.RemoveField(
            model_name="reponse",
            name="ville_arrivee",
        ),
        migrations.RemoveField(
            model_name="reponse",
            name="ville_depart",
        ),
        migrations.AddField(
            model_name="reponse",
            name="adresse_postale",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reponse",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reponse",
            name="budget",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reponse",
            name="frequence_voyage",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reponse",
            name="interet_transport",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="reponse",
            name="moyen_paiement",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="reponse",
            name="prenom",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="reponse",
            name="sensibilite_prix",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="reponse",
            name="services_souhaites",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reponse",
            name="sexe",
            field=models.CharField(
                blank=True,
                choices=[("M", "Homme"), ("F", "Femme")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="reponse",
            name="telephone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="reponse",
            name="type_colis",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="reponse",
            name="ville",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="reponse",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="reponse",
            name="nom",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
