"""
Django settings for transport_project project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- Charge le fichier .env ---
load_dotenv(dotenv_path=BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# --- Clé secrète et mode DEBUG ---
SECRET_KEY = os.environ.get('SECRET_KEY', 'changeme')
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# --- ALLOWED_HOSTS ---
if DEBUG:
    ALLOWED_HOSTS = ['*']
else:
    ALLOWED_HOSTS = [
        'web-production-f48c1.up.railway.app',
        '127.0.0.1',
        'localhost'
    ]

    CSRF_TRUSTED_ORIGINS = [
        'https://web-production-4a4b.up.railway.app',
        'http://127.0.0.1:8000',
    ]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "etude_marche",
    "suivi_colis",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "transport_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "transport_project.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

from decouple import config
import os
import dj_database_url
import sys
from django.conf import settings

# --- ENVIRONNEMENT ---
DEBUG = config("DEBUG", default=True, cast=bool)
IS_RAILWAY = config("RAILWAY_ENVIRONMENT", default=False, cast=bool)

# --- SECRET KEY ---
SECRET_KEY = config("SECRET_KEY", default="django-insecure-default-key")

# === STRIPE KEYS ===
STRIPE_PUBLIC_KEY = config('STRIPE_PUBLIC_KEY', default='')
STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY', default='')
STRIPE_WEBHOOK_SECRET = config('STRIPE_WEBHOOK_SECRET', default='')

# --- ALLOWED HOSTS & CSRF ---
if DEBUG:
    ALLOWED_HOSTS = ["*"]
    CSRF_TRUSTED_ORIGINS = []
else:
    RAILWAY_HOST = config("RAILWAY_HOST", default="web-production-4a4b.up.railway.app")
    ALLOWED_HOSTS = [RAILWAY_HOST, "127.0.0.1", "localhost"]
    CSRF_TRUSTED_ORIGINS = [f"https://{RAILWAY_HOST}", "http://127.0.0.1:8000"]

# --- DATABASE DETECTION ---
DATABASE_URL = config("DATABASE_URL", default=None)

if DATABASE_URL and IS_RAILWAY:
    print("\n🌐 Mode RAILWAY détecté — connexion à la base distante.\n")
    DATABASES = {
        "default": dj_database_url.parse(DATABASE_URL, conn_max_age=600, ssl_require=True)
    }
else:
    print("\n💻 Mode LOCAL détecté — connexion à la base PostgreSQL locale.\n")
    LOCAL_DB = {
        "NAME": config("DB_NAME", default="transport_db"),
        "USER": config("DB_USER", default="admin"),
        "PASSWORD": config("DB_PASSWORD", default="123456"),
        "HOST": config("DB_HOST", default="localhost"),
        "PORT": config("DB_PORT", default="5432"),
    }
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            **LOCAL_DB,
        }
    }

# --- Message d’info (quand on lance le serveur) ---
if 'runserver' in sys.argv:
    db_conf = DATABASES['default']
    print(
        f"✅ Django connecté à la base : {db_conf['NAME']} "
        f"({db_conf['HOST']}:{db_conf['PORT']})\n"
    )

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# === Static files (CSS, JS, images) ===
STATIC_URL = "static/"

# Dossier où Django va chercher les fichiers statiques dans chaque app
STATICFILES_DIRS = [
    BASE_DIR / "transport_project" / "static",
]

# Dossier de collecte (utilisé en production avec collectstatic)
STATIC_ROOT = BASE_DIR / "staticfiles"

# --- Sécurité HTTPS pour la prod ---
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

# --- Clé primaire par défaut ---
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# --- Configuration des logs ---
import logging

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'django-error.log',  # <-- meilleure pratique : chemin absolu
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'ERROR',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'ERROR',
            'propagate': True,
        },
        'questionnaire': {
            'handlers': ['console', 'file'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

# Pour que WhiteNoise gère les fichiers statiques en prod
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

LOGIN_URL = '/projet-transport/suivi-colis/login/'

EMAIL_BACKEND = config("EMAIL_BACKEND")
EMAIL_HOST = config("EMAIL_HOST")
EMAIL_PORT = config("EMAIL_PORT", cast=int)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", cast=bool)
EMAIL_HOST_USER = config("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL")








